name: "Multi Event Pipeline Workflow"

on:
    push:
      branches:
        - master  # or 'main' depending on your repo
        - test

    pull_request:
      branches:
        - master  # or 'main' depending on your repo

jobs:
    on-push:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
           - name: "Running on push to master/test"
             run: echo "Running on push to master/test branch"

    on-pull-request:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
           - name: "Running on pull request to master"
             run: echo "Running on pull request to master branch"
